spring:
  application:
    name: currency-converter
  main:
    banner-mode: "off"
  flyway:
    enabled: true
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

feign.client.config:
  default:
    connectTimeout: 5000
    readTimeout: 10000
    loggerLevel: basic

clients:
  currencyConverter:
    baseUrl: https://free.currconv.com
    apiKey: 5c7424a168c1aa07a825

logging:
  level:
    com.rationaldata: DEBUG

scheduler:
  fixedDelay: 300000
